### ISSUE TITLE
The workshop day

### ISSUE THREAD

**Issue by betatim** [Build-a-binder/build-a-binder.github.io#10]
Goal here is to come up with a rough guide for what the day will look like. Then make new issues and PRs to fill in the details for each part.

I'd suggest starting together as a group and then as time goes on splitting into smaller groups depending on interests. Combined with a fairly strict timekeeping so people can move between groups at the later stages(??). Then bring it all back together at the end.

Maybe the next thing is to collect ideas, no matter how ambitious they sound, for sessions. Then see how they could fit together. Having options on the day might also be a good thing.

Super rough plan to get started:

9am: Doors open
9.15am: Welcome, admin, safety, CoC, goal of the day
9.30: introduction round, who are you, what do you want to get out of this (60s per person)
9.50: Introduction to Binder, showcasing creative uses of binder
10.30: coffee break
11.00: zero 2 binder - how to get a repo with simple requirements to work on mybinder.org
Introduces tools like repo2docker, go through most common config files, urlPath, `postBuild` to fetch moderately sized data, everyone uses the same repository

12.30pm: Lunch (we order in or go to local canteen or ..?)
1.30pm: 30min quiet working time, catch up on email/twitter/phone calls
2.00pm: Welcome back
2.01: Work on your Binder - work session to get your own repository working on mybinder.org

3.00: Coffee break
3.30: ...

4.45pm  cool things that happened today, show&tell what you worked on
5.15pm Wrap up, where to next?
5.30pm Hang out (??)

**Comment by gedankenstuecke** [comment]
The super rough plan lists 9:30 twice. I guess 9:45 would be a reasonable start for the intro to binder?

**Comment by betatim** [comment]
Fixed.

**Comment by betatim** [comment]
Edited the schedule a bit. The morning now has a session where everyone uses the same demo repo and learns how to get that to work on mybinder.org. The idea is to walk everyone through the process and on the way introduce some of the tools like repo2docker.

Edited the ending and after lunch sessions as well. Show&Tell should be good and people need to have time to do emails/twitter/what not so scheduled a 30min session after lunch. For those lucky enough to not have to deal with email -> 30 more minutes for chatting and eating ice cream.
